name: Generate Datas
on:
  schedule: # execute every 12 hours
  - cron: "* */12 * * *"
  workflow_dispatch:
jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: BrVecchi
          svg_out_path: dist/github-contribution-grid-snake.svg
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Move generated files
        run: |
          mkdir -p ${{github.workspace}}/.github/svgs
          mv -f dist/github-contribution-grid-snake.svg ${{github.workspace}}/.github/svgs/
      - name: Commit files
        run: |
          git config --global user.email "bno.vecchi@gmail.com"
          git config --global user.name "BrVecchi"
          git add -A
          git commit -m "Update snake animation"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          branch: main
